### ISSUE TITLE
Map Selection

### ISSUE THREAD

**Issue by nickrbhall** [okviz/synoptic-panel-issues#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can not keep my maps on the public internet and my maps are larger than 32kb so I can not embded them using the process in Power Query that you provided.   Therefore I need to manually choose my collection of maps from your visual's GUI.

I want other visuals on my page, not only the Synoptic Panel, to be filtered so that the data presented in the other vsiuals is relevant for the sselected map.

I have read in your change notes for version 1.4.0 the following.  "We added the option to filter the report by selecting a map. Now, having multiple maps in Synoptic Panel, you can filter the data just by changing the current one from the dropdown list".

I understand from this that if I select the Map in the visuals drop down, I should be able to filter my whole report somehow by this value.  But in the toolbar menu I do not see "Filter On Map Change" as shown in your 1.4.0 change notes.  Note I have 1.5.0 installed.

I am also not clear on how I link the map selected to the rest of my data considering the above limitations i meantioned (i am having to upload my collection of maps using your visuals GUI)

Attached is a PBIX with 2 maps (apologies I can not share my real business maps) and a Matrix visual with 2 rows of data.  One row is relevant to Map1.  One row is relevantto Map2.

Can you tell me how I ensure that when I select Map1 only the Map1 row in my table is displayed and vice versa?

Thankyou

### Power BI

Power BI Desktop

### Power BI Version

2.121.644.0 64-bit (September 2023)

### Sample report

[MyTest.zip](https://github.com/okviz/synoptic-panel-issues/files/12619760/MyTest.zip)

**Comment by danieleperilli** [comment]
Unfortunately, that feature works only with the Maps field (so you need to share your maps on the public Internet).

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months (no ETA yet). This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
The current free version will not receive updates in the near future, except for security issues.

**In the new version we planned to allow users to upload their maps to a private hosting and use them to filter the report.**

**Comment by nickrbhall** [comment]
Thankyou for the update...allowing us to privately host our files will means we can use your visual at scale whereas currently we can not.  That will be an attractive addition and I look forward to this change becoming available.!
