### ISSUE TITLE
Dynamically zooming in on a specific area when a selection criterion is made in the filter panel in Power BI

### ISSUE THREAD

**Issue by ahmeddarsot** [okviz/synoptic-panel-issues#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

How do we edit the Synoptic Panel visual to dynamically zoom in on a specific floor section/area when a selection criterion is made in the filter panel? For example, if you see the image below, when we choose a Picking Area such as A then we would like it to automatically zoom into that specific warehouse area, but it just doesn’t do so unfortunately.

1.	All Picking Areas Selected

![1  All Picking Areas](https://github.com/okviz/synoptic-panel-issues/assets/160579824/c50a7bc0-7df7-4ccf-823f-573bcad4b61e)

2.	A Selected Only

![2  A Selected Only](https://github.com/okviz/synoptic-panel-issues/assets/160579824/f8a3028d-576e-492e-87ba-337299a7453f)

3.	B Selected Only

![3  B Selected Only](https://github.com/okviz/synoptic-panel-issues/assets/160579824/0c5ff45b-8a56-4a1a-b5dd-effeae815536)

We tried using Bookmarks to save each state but with no luck, it just doesn't stay zoomed in. This functionality is needed to assist the Warehouse users and make their lives easier when using the reports as most of them aren't tech savvy.

Please advise what we need to do to achieve this outcome? Thanks!

### Power BI

Power BI Desktop, Power BI service

### Power BI Version

February 2024

### Sample report

[Ahmed Sample Map.zip](https://github.com/okviz/synoptic-panel-issues/files/14342261/Ahmed.Sample.Map.zip)

### Screenshot

![1  All Picking Areas](https://github.com/okviz/synoptic-panel-issues/assets/160579824/40d37ffb-c94f-4b1b-99c8-d2f3bdb06a1d)
![3  B Selected Only](https://github.com/okviz/synoptic-panel-issues/assets/160579824/a8edd7a7-0f6c-4538-8504-eec808128f9c)
![2  A Selected Only](https://github.com/okviz/synoptic-panel-issues/assets/160579824/3255bec6-3801-4fcf-8067-4a32b4f2755c)

**Comment by danieleperilli** [comment]
Hi Ahmed, this is currently not possible. In theory, you could create 3 different maps, each of which must be available via URL, then create a column with the URLs of these maps and bind the column to the **Maps** field. Some info here: https://okviz.com/blog/introducing-synoptic-panel-v1-4/ (ref. "Loading remote maps")

**Comment by ahmeddarsot** [comment]
Excellent, will do, thanks for the feedback!

Kindly add it as a future development item though on your roadmap please.

Regards,
Ahmed Darsot
