### ISSUE TITLE
Legend sorting

### ISSUE THREAD

**Issue by Canibro** [okviz/synoptic-panel-issues#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created a visual in one page and legend looks like this. In alphabetical order, no issues.
![image](https://github.com/okviz/synoptic-panel-issues/assets/160606537/6b6d3014-fc4d-496e-a8d5-fdc7be54e598)

I had to create another page with same visual, data, picture but somehow that I am not aware the legend started to change the order like this
![image](https://github.com/okviz/synoptic-panel-issues/assets/160606537/7b60ca7a-5061-4f0f-bb8e-1c3ff83bdbae)

I found out that the measure field was sorted by order in my second visual but not sorted in the first one
Picture of "show as a table" of legend in alphabetical order
![image](https://github.com/okviz/synoptic-panel-issues/assets/160606537/6fa3cfcc-4f8c-4720-b45c-5bb92483c7ee)

Picture of second visual not in alphabetical order
![image](https://github.com/okviz/synoptic-panel-issues/assets/160606537/5f584adc-e7f0-4bd3-8546-eb0c2990173f)

How can I select/force not to sort by the measure field? 
Is it my data or the synoptic panel? 

Thank you

### Power BI

Power BI Desktop

### Power BI Version

 2.126.927.0 64-bit (February 2024)

### Sample report

I will create it upon request

**Comment by danieleperilli** [comment]
We are working on a new premium version that will replace the current one and will include several improvements, including the suggested one. The ETA is Q2 2024.
