### ISSUE TITLE
Cross Report Drill through

### ISSUE THREAD

**Issue by shankargv87** [okviz/synoptic-panel-issues#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently Drill through context menu is not displayed when I right click on map. 

I'm expecting like below.

![image](https://github.com/okviz/synoptic-panel-issues/assets/34228085/c678626e-574b-4913-8298-60bc6ac35684)

### Power BI

Power BI Desktop

### Power BI Version

Power BI Desktop RS Jan 2023

### Sample report

In the attached sample report, I have two pages "Maps" and "Table". I'm trying to drill through from "Maps" page. 
[synopticPanelByOKViz.1.5.0.0.zip](https://github.com/okviz/synoptic-panel-issues/files/14368319/synopticPanelByOKViz.1.5.0.0.zip)

### Screenshot

Maps page

![image](https://github.com/okviz/synoptic-panel-issues/assets/34228085/1bfa97ec-a45e-4570-aa38-0f13d0bb57c0)

Table page

![image](https://github.com/okviz/synoptic-panel-issues/assets/34228085/ba64c67f-8d70-4bab-858b-14a637ddfc15)

I enabled "Cross-report" option in "Table" page. But context menu not showing up in Map visual.

**Comment by danieleperilli** [comment]
We are working on a new premium version that will replace the current one and will include several improvements, including the suggested one. The ETA is Q2 2024.

**Comment by shankargv87** [comment]
@danieleperilli, 

Thanks for the reply. It would be helpful if you could provide the 'drill-through' context menu in the free version.

**Comment by danieleperilli** [comment]
Sorry, this is not in our current plans.
