### ISSUE TITLE
Inquiry Regarding Displaying Images in Synoptic Panel Visual in Power BI

### ISSUE THREAD

**Issue by RodBismart** [okviz/synoptic-panel-issues#14]
### The feature request

The ability to display images within the Synoptic Panel visual in Power BI.

### Proposed solution

Implement functionality within the Synoptic Panel visual to allow users to display images stored in Azure Blob storage alongside seating arrangements and other information.

### Additional context

I am writing to inquire about the possibility of displaying images within the Synoptic Panel visual in Power BI. Currently, I am using the Synoptic Panel visual to visualize cafeteria layouts, including the seating arrangement of each user along with their dietary information. However, I am encountering difficulties in displaying the user's photo within the Synoptic Panel visual or to create a Tooltip to do it

**Comment by danieleperilli** [comment]
We are working on a new premium version that will replace the current one and will include several improvements, including the ability to display report tooltips. At that point, you can create a custom report with the images and connect as tooltip. The ETA is Q2 2024.
