### ISSUE TITLE
Can't find "Values" field in Synoptic Panel v1.5.0

### ISSUE THREAD

**Issue by akshay996** [okviz/synoptic-panel-issues#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just today I got introduced to Synoptic Panel and I was referencing to the available online videos to create a visualization:

https://www.youtube.com/watch?v=MYwNVCyZug0
https://www.youtube.com/watch?v=DKTPvhzS3lU

The issue I am facing is that I don't see "Values" field in Synoptic v1.5.0 and hence I am not sure how to link the values to the SVG visual I created. Can someone please guide me through it?

![image](https://github.com/okviz/synoptic-panel-issues/assets/59548002/f07640a6-cdd1-4343-a958-8b2ad1e8d587)

My use-case: I am trying to color the segments in S with respective dates Incident value - if there are 0 incidents then green else it should be red.

![image](https://github.com/okviz/synoptic-panel-issues/assets/59548002/917b2f29-219c-4999-814d-7be9e4ec9782)
![image](https://github.com/okviz/synoptic-panel-issues/assets/59548002/281b01f2-1714-4480-8f5b-7c90bbed79ce)

### Power BI

Power BI Desktop

### Power BI Version

2.128.1177.0 64-bit (April 2024)

### Sample report

![Screenshot 2024-04-29 144450](https://github.com/okviz/synoptic-panel-issues/assets/59548002/fffc7f1c-abac-4cf6-a6cc-7275f73d8a6a)

**Comment by danieleperilli** [comment]
You just have to use the "Measure" role.
