### ISSUE TITLE
Tardy Map

### ISSUE THREAD

**Issue by Robert-Givens** [okviz/synoptic-panel-issues#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a table with the categories and I have created a SVG file in visio with the shapes named, when I hover over the map I see the data in there. I created a measure that aggregates tardies, but the data does not map to the visual. All areas are unmatched. 

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.128.952.0 64-bit (April 2024)

### Sample report

I have emailed "Synoptic Sample.PBIX" to the email address.
![THS MAP](https://github.com/okviz/synoptic-panel-issues/assets/96450792/22d11937-d4b4-484e-a85c-703a52530913)
[Tardies.xlsx](https://github.com/okviz/synoptic-panel-issues/files/15251066/Tardies.xlsx)

**Comment by danieleperilli** [comment]
You need to assign the exact value of the record you wish to match to each ID of the element you wish to color. 
In the example below, the area with ID: **shape15-312** should be named **5204**, BUT here is a problem: area IDs don't work with numbers, you need the IDs to start with a non-numeric character.
![tardies](https://github.com/okviz/synoptic-panel-issues/assets/9072177/a26c7d96-5c99-44df-a6c0-c61df7557743)

**Comment by Robert-Givens** [comment]
I used the synoptic designer and that worked instead of Visio. 
![image](https://github.com/okviz/synoptic-panel-issues/assets/96450792/78b7e493-c38c-4cf6-a08b-df925a2267cf)
I tried switching between two maps on the visual, but I don't know how to filter the data based on the map selection. I read the documentation and was still lost.

**Comment by danieleperilli** [comment]
You need to use remote maps and have a column which contains  field for each map URL. Then you need to connect this field to the visual's data role Maps.  https://okviz.com/blog/introducing-synoptic-panel-v1-4/ (Loading remote maps)
