### ISSUE TITLE
Custom  Tooltip

### ISSUE THREAD

**Issue by mahdirahimimoghadam** [okviz/synoptic-panel-issues#2]
### The feature request

I used synoptic panel to show an offline map of country  with csv file.
I think its better if we can customization on tooltip, like showing another svg on tooltip 
for example when I hovered on a province, appearance another svg that show cities.

### Proposed solution

It can be utilize in many situations.

**Comment by danieleperilli** [comment]
Unfortunately, this is not technically feasible.
