### ISSUE TITLE
Issue with SVG Map in Power BI Report

### ISSUE THREAD

**Issue by mtavana66** [okviz/synoptic-panel-issues#20]
![Uploading World.svg…]()
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am writing to seek assistance regarding an issue I encountered while utilizing the features of your website, specifically the "SYNOPTIC DESIGNER FOR POWER BI.", In order to complete my task, I required a world map, which I obtained through your platform in SVG format.

However, despite my efforts to integrate the map into my Power BI report, I have encountered a persistent problem. The map does not function as expected, and any modifications I attempt to make do not reflect in the report.

To provide further context, I have attached the SVG file for your reference. I would greatly appreciate it if you could investigate this matter and provide guidance on how to resolve the issue. Additionally, if there are any specific steps or best practices I should follow when incorporating SVG files into Power BI reports, please advise accordingly.

Thank you for your attention to this matter. I look forward to your prompt response and resolution of the issue.

### Power BI

Power BI Desktop

### Power BI Version

2.124.1960.0 64-bit (January 2024)

### Sample report

[Uploading test.zip…]()

### Screenshot

![Uploading Screenshot 2024-05-13 151416.jpg…]()

### Anything else?

![World](https://github.com/okviz/synoptic-panel-issues/assets/77035871/dc34514f-3459-4dc9-bd42-add615d3e208)

**Comment by danieleperilli** [comment]
Sorry, I can't see any files uploaded.

**Comment by mtavana66** [comment]
![World](https://github.com/okviz/synoptic-panel-issues/assets/77035871/0073b7de-dc49-4903-9405-97bdb1488a56)
![Screenshot 2024-05-13 151416](https://github.com/okviz/synoptic-panel-issues/assets/77035871/6823dbb4-5bce-4097-8b4a-1373899a7a1d)
[test.zip](https://github.com/okviz/synoptic-panel-issues/files/15302745/test.zip)
Hi
Uploaded them again

**Comment by danieleperilli** [comment]
The ID of the areas in the SVG must match the values on you data column.
![screen2024-05-14-000363](https://github.com/okviz/synoptic-panel-issues/assets/9072177/0b3f2a56-7596-4c48-affc-7fb854b87143)
