### ISSUE TITLE
Unmatch object

### ISSUE THREAD

**Issue by SylvainLemasson** [okviz/synoptic-panel-issues#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I tried to match a scheme that I convert in SVG with a database on Power BI. I change the ID of shapes in the SVG to give them the same name as my collum tag on my database. But nothing match. I don't understand why.

Regards

### Power BI

Power BI Desktop

### Sample report

[SVG.zip](https://github.com/user-attachments/files/16425533/SVG.zip)

### Screenshot

![Extract_synoptic](https://github.com/user-attachments/assets/1e33e607-0387-4046-9bda-610c5d8cb856)
![ExtractBD_PBI](https://github.com/user-attachments/assets/03a5b5a4-1e3c-408a-bd56-c467c0ca7a46)
![ExtractInkscape](https://github.com/user-attachments/assets/252f6d3d-28b0-4ab8-b602-f1feb07c129a)

**Comment by danieleperilli** [comment]
Hi Sylvain, it seems there isn't a correct match between areas ids and data.
![screen2024-07-30-000613](https://github.com/user-attachments/assets/134dd2b8-0251-4ee8-98fc-864c7732d1f0)
