### ISSUE TITLE
How to code for state and state colors in synoptic panel?

### ISSUE THREAD

**Issue by sl33pyZzz** [okviz/synoptic-panel-issues#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi
 
Is there an example of how to code for state colour in Synoptic Panel?
 
For example, I have two tables: category and state. The state contains seven different states, so I need seven colours. How do I code them?

Do note if the data colour is to set colours for a category, not state.

### Power BI

Power BI Desktop

### Sample report

-

**Comment by danieleperilli** [comment]
Next version will support Power BI conditional formatting. ETA is end of september.
