### ISSUE TITLE
Increase maximum number of States

### ISSUE THREAD

**Issue by nlau2000** [okviz/synoptic-panel-issues#26]
### The feature request

Currently the synoptic panel only supports up to 5 states for coloring. It would be amazing to have a few more states to visualize data with more than 5/6 categories.

![image](https://github.com/user-attachments/assets/9842378c-8eca-4182-9e7f-a329cbb41b22)

### Proposed solution

If possible, please increase the maximum amount to ~10+. This would allow for much more flexibility.

**Comment by danieleperilli** [comment]
The new version will allow to use Power BI conditional formatting. New ETA is end of October.
