### ISSUE TITLE
Map code not refreshing on the visual when switching 

### ISSUE THREAD

**Issue by annemaripius** [okviz/synoptic-panel-issues#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The svg files are embbeded as code to the semantic model.  The code is used on the Map field of the visual. When switching between the maps using a slicer, the map image does not refresh itself.

When moving to a blank value bitween individual map, so that the visual gets no value, the maps change properly.

How to switch between the maps without the additional reset step? Example attatched. Thanks!

### Power BI

Power BI Desktop

### Power BI Version

august 2024

### Steps To Reproduce

1. open the example pbix
2. using the slicer, click through G-B-B2 in any combination - the map image does not refresh according to the slicer selection.
3. using the slicer, click through G-blank-B-blank-B2-blank - the map image refreshes according to the slicer selection.

### Sample report

[example_not_refreshing.zip](https://github.com/user-attachments/files/16908938/example_not_refreshing.zip)

**Comment by annemaripius** [comment]
Hi, can you say whether it is a bug or some kind of misusage? Really struggling with getting the visuals to update with slicer change.

**Comment by danieleperilli** [comment]
Hi @annemaripius, but weren't you on the preview list for the new version of Synoptic Panel?

**Comment by annemaripius** [comment]
@danieleperilli I am, but I’m using the current version for a client and cannot get this to work.

**Comment by danieleperilli** [comment]
Since the version you are using is going to be deprecated in a few weeks, we cannot provide support for it.
