### ISSUE TITLE
Does the Synoptic Panel Visual Support streaming data?  The measure on hover reflects the incorret value.

### ISSUE THREAD

**Issue by elfohl** [okviz/synoptic-panel-issues#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My name is Liz and I work at Microsoft.  I am putting together a Synoptic Pannel (my first one), of a simple race track.  (I created this simple visual.)

I’m trying to get my streaming data to move around the track.  I’m speaking at an automotive event about Power BI and thought this would be a cool use case.
Everything works great.  My visual works great and I’ve plotted all my “areas” on the loop.

I’m struggling with the measure, and how it works.

**TotalPoint = sum(RealTimeData[AllPoint])**

 What should the measure be representative of?
•	The total of all cars, which would be 10… which if I put that value in a card I see 10.
•	Or total for that car, visual above.
•	It’s something else all together and I’m not clear where this is coming from and how the visual sees the measure?

 

### Power BI

Power BI Desktop

### Power BI Version

2.133.902.0 64-bit (September 2024)

### Steps To Reproduce

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/63f387d7-5f9b-424d-af77-2e5a19abe503">

### Sample report

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/ba8564a0-dd21-41db-b896-6cc90367bd4b">

### Screenshot

<img width="1217" alt="Synoptic Panel setup" src="https://github.com/user-attachments/assets/2b8003be-0cff-4ae2-aeef-a4144cc354cd">

### Anything else?

Maybe the synoptic panel doesn't support streaming data sources?

**Comment by danieleperilli** [comment]
Synoptic Panel can highlight existing SVG shapes by matching their id with data. It's not able to move shapes around, sorry.

**Comment by elfohl** [comment]
I was able to figure it out.

I needed to change the area number to the area name I wanted and include a dax measure to only “fill in” the last received car, now the bubbles look like they are moving.  😊
***@***.***
