### ISSUE TITLE
Visual doesn't load to PBI Report Server

### ISSUE THREAD

**Issue by amcymbron** [okviz/synoptic-panel-issues#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I have a PBI dashboard that uses the custom visual Synoptic Panel by OKViz. When I have the report open in Power BI Desktop, the visual works perfectly. When I save the dashboard on the report server, all the elements that use this custom visual are blank. However, if I publish the dashboard to Power BI Service, the visual works perfectly. I posted the problem on the Microsoft Power BI Forum, and they told me to update to the most recent version of PowerBI Report Server. I did that (I updated both the report server and the power bi desktop to the september 2024 version). On the desktop, I created a test file, and it looks like this:

![image](https://github.com/user-attachments/assets/6fa7f1a5-7686-45e2-96ba-e96cc5e23221)

When I save it to the report server, it looks like this:

![image](https://github.com/user-attachments/assets/042b086b-9708-4789-aac6-6aa5cf8d6a34)

The problem happens with local maps, and also with maps that are SVG files published on the web.

Do you have any idea how to correct the problem? I also attached another example (both the Excel file with the dummy data, and the pbix file) that I tried and didn't work in PBI Report Server, with maps. 

Thanks,

### Power BI

Power BI Desktop, Power BI service

### Sample report

[pbi_example.zip](https://github.com/user-attachments/files/17479850/pbi_example.zip)

**Comment by danieleperilli** [comment]
I'm afraid the only way is to open a ticket with Microsoft. If the visual works well in Power BI Service and Desktop, but not in Power BI Report Server, the problem is not related to our code. I am sorry to pass the buck to others, but there is nothing we can do in this case.

**Comment by amcymbron** [comment]
Hi!

I concluded that the problem was related with the browser. In Google Chrome the visual wouldn't load, but in any other browser the visual works as expected.
