### ISSUE TITLE
“Filter on map change” feature is missing

### ISSUE THREAD

**Issue by kennethtangfrasers** [okviz/synoptic-panel-issues#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im trying to find the “Filter on map change” feature but I couldn’t find it.

This screenshot below is what I read. (see attached)

Attached is my powerbi screenshot. But I can’t find the “filter on map change” function. 
![what i read](https://github.com/okviz/synoptic-panel-issues/assets/157475174/897ad84f-decd-467d-a890-9281825c6923)
![my power bi screen](https://github.com/okviz/synoptic-panel-issues/assets/157475174/debd3787-cebc-44cf-9a09-e2e208d5a764)

### Power BI

Power BI Desktop

### Power BI Version

2.124.1554.0 64-bit (December 2023)

### Steps To Reproduce

see attached screenshot

### Sample report

[floor plan.zip](https://github.com/okviz/synoptic-panel-issues/files/14021447/floor.plan.zip)

### Screenshot

![what i read](https://github.com/okviz/synoptic-panel-issues/assets/157475174/4c582848-b657-4557-a60a-c9ed6252d527)
![my power bi screen](https://github.com/okviz/synoptic-panel-issues/assets/157475174/a1ed9feb-ec7a-438a-a806-073135c6e93f)

**Comment by danieleperilli** [comment]
That settings is visible and works only if you bind a column with map URLs as values to the "Maps" data role (in the fields panel).
